name: master-merged-action

env:
  PROJECT_NAME: ${{ 'PodFrameworkTest' }}
  OUTPUTFOLDER: ${{ './Frameworks' }}
  PROJECT_STYLE: ${{ 'project' }}
  PFOJECT_FILE: ${{ 'xcodeproj' }}
  


on:
 push:
   branches: [ master ]
#   pull_request:
#     branches: [ master ]
#     types : [ closed ]

jobs:
  build:
#     if: github.event.pull_request.merged == true
    runs-on: macos-latest

    steps:
     - uses: actions/checkout@v2
     - name: Install the Apple certificate and provisioning profile
       env:
          BUILD_CERTIFICATE_BASE64: ${{ 'developCert.p12' }}
          P12_PASSWORD: ${{ '1111' }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ 'skt_wile.mobileprovision' }}
          KEYCHAIN_PASSWORD: ${{ '1111' }}
       run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
#      - name: Set Xcode Version 
#        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app
     - name: Test Code
       run: |
          xcodebuild test -project "PodFrameworkTest.xcodeproj" -scheme "PodFrameworkTest" -destination "platform=iOS Simulator,name=iPhone 11"
     - name: Archive 
       run: |
          xcodebuild archive -$PROJECT_STYLE $PROJECT_NAME.$PFOJECT_FILE -scheme $PROJECT_NAME -configuration "Debug" -destination="generic/platform=iOS" -archivePath $OUTPUTFOLDER/ios.xcarchive -derivedDataPath /tmp/iphoneos -sdk iphoneos arch=arm64 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES 
          xcodebuild archive -$PROJECT_STYLE $PROJECT_NAME.$PFOJECT_FILE -scheme $PROJECT_NAME -configuration "Debug" -destination="generic/platform=iOS Simulator" -archivePath $OUTPUTFOLDER/iossimulator.xcarchive -derivedDataPath /tmp/iphonesimulator -sdk iphonesimulator arch=x86_64 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES 
     - name: Universal Framework
       run: |
          xcodebuild -create-xcframework -framework $OUTPUTFOLDER/ios.xcarchive/Products/Library/Frameworks/$PROJECT_NAME.framework -framework $OUTPUTFOLDER/iossimulator.xcarchive/Products/Library/Frameworks/$PROJECT_NAME.framework  -output $OUTPUTFOLDER/$PROJECT_NAME.xcframework


 
