name: master-merged-action

env:
  PROJECT_NAME: ${{ 'PodFrameworkTest' }}
  OUTPUTFOLDER: ${{ './Frameworks' }}
  PROJECT_STYLE: ${{ 'workspace' }}
  PFOJECT_FILE: ${{ 'xcworkspace' }}
  XC_VERSION: ${{ '11.6' }}
  XC_ARCHIVE: ${{ 'HoneyPot.xcarchive' }}
#   XC_SCHEME: ${{ 'HoneyPot' }}


on:
#  push:
#    branches: [ master ]
#   pull_request:
#     branches: [ master ]
#     types : [ closed ]

jobs:
  build:
#     if: github.event.pull_request.merged == true
    runs-on: macos-latest

    steps:
#      - uses: actions/checkout@v2
#      - name: Set Xcode Version 
#        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app
#      - name : Install Dependencies 
#        run: |
#         pod repo update
#         pod install 
#        shell: bash 
     - name: Test Code
       run: |
          xcodebuild test -project PodFrameworkTest.xcodeproj -scheme PodFrameworkTest -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5'
     - name: Archive 
       run: |
          xcodebuild archive -$PROJECT_STYLE $PROJECT_NAME.$PFOJECT_FILE -scheme $PROJECT_NAME -destination="generic/platform=iOS" -archivePath $OUTPUTFOLDER/ios.xcarchive -derivedDataPath /tmp/iphoneos -sdk iphoneos arch=arm64 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES 
          xcodebuild archive -$PROJECT_STYLE $PROJECT_NAME.$PFOJECT_FILE -scheme $PROJECT_NAME -destination="generic/platform=iOS Simulator" -archivePath $OUTPUTFOLDER/iossimulator.xcarchive -derivedDataPath /tmp/iphonesimulator -sdk iphonesimulator arch=x86_64 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES 
     - name: Universal Framework
       run: |
          xcodebuild -create-xcframework -framework $OUTPUTFOLDER/ios.xcarchive/Products/Library/Frameworks/$PROJECT_NAME.framework -framework $OUTPUTFOLDER/iossimulator.xcarchive/Products/Library/Frameworks/$PROJECT_NAME.framework  -output $OUTPUTFOLDER/$PROJECT_NAME.xcframework


 
