name: master-merged-action

env:
  PROJECT_NAME: ${{ 'PodFrameworkTest' }}
  OUTPUTFOLDER: ${{ './Frameworks' }}
  
  CERTIFICATE_PATH: ${{ '.github/secret/build_certificate.p12' }}
  PP_PATH: ${{ '.github/secret/build_pp.mobileprovision' }}
  KEYCHAIN: ${{ 'test.keychain' }}
  
  CERTS_BASE64: ${{ secrets.DEVELOP_CERT }}
  PROVISONING_BASE64: ${{ secrets.BASE64_PROVISIONING }}
  
  CERTS_ENCRYPTION_PWD: ${{ secrets.CERT_PASSWORD }} 
  PROVISION_ENCRYPTION_PWD: ${{ secrets.CERT_PASSWORD }} 
  CERTS_EXPORT_PWD: ${{ secrets.CERT_PASSWORD }}


on:
 push:
   branches: [ master ]
#   pull_request:
#     branches: [ master ]
#     types : [ closed ]

jobs:
  build:
#     if: github.event.pull_request.merged == true
    runs-on: macos-latest

    steps:
     - uses: actions/checkout@v2
     - name: Decoding Certificate and Provisioning
       run: |
           echo -n "$CERTS_BASE64" | base64 --decode --output $CERTIFICATE_PATH
           echo -n "$PROVISONING_BASE64" | base64 --decode --output $PP_PATH
#      - name: Configure Keychain
#        run: |
#           security create-keychain -p "" "$KEYCHAIN"
#           security list-keychains -s "$KEYCHAIN"
#           security default-keychain -s "$KEYCHAIN"
#           security unlock-keychain -p "" "$KEYCHAIN"
#           security set-keychain-settings
# #      - name: Set Xcode Version 
# #        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app
#      - name: Configure p12
#        run: |    
#           security import "$CERTIFICATE_PATH" -k "$KEYCHAIN" -P "$CERTS_EXPORT_PWD" -A
#           security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN"
#      - name: Configure Provisioning
#        run: |
#           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
#           cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
#      - name: Test Code
#        run: |
#          xcodebuild test -project "$PROJECT_NAME".xcodeproj -scheme "$PROJECT_NAME" -destination "platform=iOS Simulator,name=iPhone 11"
#      - name: Archive 
#        run: |
#           xcodebuild archive -project "$PROJECT_NAME".xcodeproj -scheme "$PROJECT_NAME" -configuration "Debug" -destination="generic/platform=iOS" -archivePath "$OUTPUTFOLDER"/ios.xcarchive -derivedDataPath /tmp/iphoneos -sdk iphoneos arch=arm64 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES 
#           xcodebuild archive -project "$PROJECT_NAME".xcodeproj -scheme "$PROJECT_NAME" -configuration "Debug" -destination="generic/platform=iOS Simulator" -archivePath "$OUTPUTFOLDER"/iossimulator.xcarchive -derivedDataPath /tmp/iphonesimulator -sdk iphonesimulator arch=x86_64 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES 
#      - name: Check file existence
#        uses: andstor/file-existence-action@v1
#        with:
#           files: "./Frameworks/ios.xcarchive/Products/Library/Frameworks/PodFrameworkTest.framework, ./Frameworks/iossimulator.xcarchive/Products/Library/Frameworks/PodFrameworkTest.framework "
#      - name: File exists
#        if: steps.check_files.outputs.files_exists == 'true'
#         # Only runs if all of the files exists
#        run: |
#           echo All files exists!
     - name: Framework Remove
       uses: EndBug/add-and-commit@v7
       with:
          author_name: Anna
          author_email: togass7@google.com
          remove : './Frameworks/* --force'
     - name : universal Framework
       run: |
           xcodebuild -create-xcframework -framework "$OUTPUTFOLDER"/ios.xcarchive/Products/Library/Frameworks/$PROJECT_NAME.framework -framework "$OUTPUTFOLDER"/iossimulator.xcarchive/Products/Library/Frameworks/$PROJECT_NAME.framework  -output "$OUTPUTFOLDER"/"$PROJECT_NAME".xcframework          
     - name: Framework Add
       uses: EndBug/add-and-commit@v7
       with:
          author_name: Anna
          author_email: togass7@google.com
          message: 'Framework Add'
          add: './Frameworks/PodFrameworkTest.xcframework -- force'
          cwd: './Frameworks/'
#      - name: Upload Artifact 
#        uses: actions/upload-artifact@v2
#        with: 
#         name: Artifacts
#         path: ./artifacts



 
